/**
 * The OpenNext build output, declared so `cloudflare/worker.ts` can import it.
 *
 * `.open-next/worker.js` is generated by `opennextjs-cloudflare build` and does
 * not exist on a clean checkout, so TypeScript cannot infer anything from it.
 * Declaring the shape here is what lets the wrapper be type-checked in CI
 * *before* the build runs — which is the whole point of checking it at all.
 *
 * The three exports match the adapter's generated worker template
 * (`node_modules/@opennextjs/cloudflare/dist/cli/templates/worker.d.ts`). If a
 * future adapter version renames one, this file is where the mismatch surfaces
 * as a type error rather than as a "class not found" at deploy time.
 */
declare module '*/.open-next/worker.js' {
  const handler: {
    fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response>;
  };

  /** Durable Object backing the incremental cache's revalidation queue. */
  export const DOQueueHandler: DurableObjectConstructor;
  /** Durable Object backing the sharded tag cache. */
  export const DOShardedTagCache: DurableObjectConstructor;

  export default handler;
}

type DurableObjectConstructor = new (state: DurableObjectState, env: unknown) => DurableObject;
