/**
 * The Cloudflare Worker entrypoint.
 *
 * OpenNext compiles the Next.js application into `.open-next/worker.js`, which
 * exports a `fetch` handler and nothing else. Everything a production
 * deployment needs *besides* serving HTTP has to be added around it, and this
 * is that wrapper:
 *
 *   - `fetch`    — delegated to OpenNext, unchanged.
 *   - `queue`    — the Cloudflare Queues consumer that runs background jobs.
 *   - `scheduled`— Cron Triggers: the sweep, reconciliation, nightly work.
 *
 * ## Why wrap rather than configure
 *
 * `queue` and `scheduled` are Worker-level exports. There is no adapter option
 * that adds them, and putting the job logic in an HTTP route instead would mean
 * a Cron Trigger has to make an authenticated request to itself — paying a
 * round trip and a second isolate to do work this isolate could have done.
 *
 * ## Build order
 *
 * `.open-next/worker.js` does not exist until `opennextjs-cloudflare build` has
 * run, so this file's import fails on a clean checkout. That is deliberate:
 * `npm run cf:build` runs the OpenNext build first, and `wrangler deploy`
 * depends on it. See docs/deployment.md.
 */

// Generated by `opennextjs-cloudflare build`; its shape is declared in
// `cloudflare/open-next.d.ts` so this file type-checks before the build runs.
import openNextHandler from '../.open-next/worker.js';

/**
 * Durable Object classes, re-exported.
 *
 * These are not decoration. Wrangler resolves `durable_objects.bindings`
 * against the classes exported by `main`, and `main` is this file — so a
 * binding whose class is only exported by the *generated* worker resolves to
 * nothing and the deploy fails with "class not found". The incremental cache's
 * revalidation queue and the sharded tag cache both live behind these.
 */
export { DOQueueHandler, DOShardedTagCache } from '../.open-next/worker.js';

export interface Env {
  JOB_QUEUE: Queue<JobMessage>;
  EMAIL_QUEUE: Queue<JobMessage>;
  CRON_SECRET?: string;
  [key: string]: unknown;
}

interface JobMessage {
  jobId: string;
  kind: string;
}

/**
 * The queue consumer.
 *
 * ## Per-message acknowledgement, not per-batch
 *
 * Returning normally acks the whole batch; throwing retries the whole batch.
 * Neither is right when nine of ten messages succeeded, so every message is
 * explicitly `ack()`ed or `retry()`ed. Without this, one poison message drags
 * nine successful jobs through a retry — and they are only idempotent, not
 * free.
 *
 * ## What "retry" means here
 *
 * Only infrastructure failures. A job whose *handler* failed has already been
 * scheduled for retry in the database with proper backoff, so the message is
 * acked — retrying the message as well would run it twice at once. `retry()`
 * is reserved for the case where we could not reach the database at all.
 *
 * ## Duplicate delivery
 *
 * Cloudflare Queues is at-least-once. `runOne` claims with a `status =
 * 'QUEUED'` predicate, so the duplicate claims nothing and returns `'gone'`,
 * which is acked. The database is what makes the delivery guarantee harmless.
 */
async function queue(batch: MessageBatch<JobMessage>, env: Env): Promise<void> {
  const { runOne } = await import('@/lib/jobs/worker');
  const { flush } = await import('@/lib/monitoring/sentry');

  await Promise.all(
    batch.messages.map(async (message) => {
      const { jobId, kind } = message.body ?? {};

      if (!jobId) {
        // Malformed message. Retrying it forever fills the DLQ with garbage.
        message.ack();
        return;
      }

      try {
        const outcome = await runOne(jobId, `cf-queue-${batch.queue}`);

        if (outcome === 'retry' && message.attempts >= 3) {
          // Three failed attempts to even claim the row. Let it fall to the
          // dead-letter queue where a human will see it; the job row itself is
          // untouched and the cron sweep is still the safety net.
          message.retry();
          return;
        }

        message.ack();
      } catch (error) {
        console.error(
          JSON.stringify({ level: 'error', message: 'queue.consumer_failed', jobId, kind }),
        );
        void error;
        message.retry({ delaySeconds: Math.min(2 ** message.attempts * 5, 300) });
      }
    }),
  );

  // The isolate can be frozen the instant this returns, so any in-flight error
  // report has to be settled here or it is simply lost.
  await flush(1_000);
  void env;
}

/**
 * Cron Triggers.
 *
 * The schedule string is matched against `wrangler.jsonc`'s `triggers.crons`,
 * in order, so adding one there without adding it here silently does nothing —
 * hence the `default` branch, which is loud.
 *
 * Each branch is wrapped so one failing schedule cannot take the others with
 * it: they run in the same isolate but they are not the same job.
 */
async function scheduled(
  event: ScheduledController,
  env: Env,
  ctx: ExecutionContext,
): Promise<void> {
  const { flush, captureException } = await import('@/lib/monitoring/sentry');

  const run = async () => {
    switch (event.cron) {
      // Every minute: drain anything the push path missed. This is the floor
      // that makes Cloudflare Queues allowed to fail.
      case '* * * * *': {
        const { drain } = await import('@/lib/jobs/worker');
        await drain({ maxJobs: 25, maxMs: 25_000, concurrency: 4 });
        return;
      }

      // Every 15 minutes: give back stock held by abandoned checkouts.
      case '*/15 * * * *': {
        const { releaseExpiredReservations } = await import('@/services/order.service');
        await releaseExpiredReservations();
        return;
      }

      // Nightly: extend Klarna authorisations that would otherwise lapse before
      // the goods ship, and reconcile anything whose push we missed.
      case '0 6 * * *': {
        const { extendExpiringAuthorizations } = await import('@/services/payment.service');
        await extendExpiringAuthorizations();
        return;
      }

      default:
        captureException(new Error(`Unhandled cron trigger: ${event.cron}`), {
          level: 'warning',
          tags: { cron: event.cron },
        });
    }
  };

  try {
    await run();
  } catch (error) {
    captureException(error, { transaction: `cron ${event.cron}`, tags: { cron: event.cron } });
    throw error;
  } finally {
    // `waitUntil` keeps the isolate alive for the flush without holding the
    // scheduled handler open.
    ctx.waitUntil(flush(2_000));
  }

  void env;
}

const handler = {
  fetch: openNextHandler.fetch,
  queue,
  scheduled,
};

export default handler;
